Kindle.create!( inventory_id: 'OSX0049', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX0050', status: 'free')
Kindle.create!( inventory_id: 'OSX00100', status: 'free')
Kindle.create!( inventory_id: 'OSX00120', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00121', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00255', status: 'free')
Kindle.create!( inventory_id: 'OSX00300', status: 'free')
Kindle.create!( inventory_id: 'OSX00301', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00302', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00303', status: 'free')
Kindle.create!( inventory_id: 'OSX00304', status: 'free')
Kindle.create!( inventory_id: 'OSX00305', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00310', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00315', status: 'free')
Kindle.create!( inventory_id: 'OSX00320', status: 'free')
Kindle.create!( inventory_id: 'OSX00321', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00322', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00323', status: 'free')
Kindle.create!( inventory_id: 'OSX00400', status: 'free')
Kindle.create!( inventory_id: 'OSX00450', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00500', status: 'borrowed')
Kindle.create!( inventory_id: 'OSX00600', status: 'free')
Kindle.create!( inventory_id: 'OSX00700', status: 'free')
Kindle.create!( inventory_id: 'OSX00800', status: 'borrowed')


